### ISSUE TITLE
filtering tests fail

### ISSUE THREAD

**Issue by tarnap** [4teamwork/django-eventary#49]
```
FAIL: test_single_day_event_filters (eventary.tests.test_pagination_and_filtering.EventFilterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/verges/projects/djangoapps/django-eventary/eventary/tests/test_pagination_and_filtering.py", line 189, in test_single_day_event_filters
    self._test_filter_run(events, proposals, self.single_filter_data())
  File "/home/verges/projects/djangoapps/django-eventary/eventary/tests/test_pagination_and_filtering.py", line 126, in _test_filter_run
    message)
AssertionError: 5 != 0 : expected 0 events, filters from & to

----------------------------------------------------------------------
Ran 18 tests in 41.356s
```

This test fails since the validation of the event dates and times.

**Comment by tarnap** [comment]
```
.................> /home/verges/projects/djangoapps/django-eventary/eventary/tests/test_pagination_and_filtering.py(126)_test_filter_run()
-> self.assertEquals(
(Pdb) [(e.eventtimedate.start_date, e.eventtimedate.end_date) for e in events]                                                                                                                                                                
[(datetime.date(2017, 3, 7), None), (datetime.date(2017, 3, 8), None), (datetime.date(2017, 3, 9), None), (datetime.date(2017, 3, 10), None), (datetime.date(2017, 3, 11), None)]
(Pdb) filter_parameters
{'filter-from_date': '2017-03-07', 'filter-to_date': '2017-03-06'}
```

Aha!

Since the sent filter data is incorrect the events are not filtered at all and we get 5 events instead of the expected 0 events!
